FROM node:latest

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY . .

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN npm i --production
CMD npm run prod
